#! /bin/sh

# I used /etc/init.d/sshd to get inspiration on how this should be written :P

### BEGIN INIT INFO
# Provides:             gitlabnssd fetchgitlabkeys
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    TODO
### END INIT INFO

set -e

test -x /bin/gitlabnssd || exit 0

umask 022

. /lib/lsb/init-functions

# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

check_dev_null() {
    if [ ! -c /dev/null ]; then
        if [ "$1" = log_end_msg ]; then
            log_end_msg 1 || true
        fi
        if ! run_by_init; then
            log_action_msg "/dev/null is not a character device!" || true
        fi
        exit 1
    fi
}

check_privsep_dir() {
    # Create the PrivSep empty dir if necessary
    if [ ! -d /run/gitlabnssd ]; then
        mkdir /run/gitlabnssd
        chmod 0755 /run/gitlabnssd
    fi
}

export PATH="${PATH:+$PATH:}/usr/bin:/bin"

case "$1" in
  start)
        check_privsep_dir
        check_dev_null
        log_daemon_msg "Starting GitLab Daemon" "gitlabnssd" || true
        if start-stop-daemon --start --quiet --oknodo --chuid 0:0 --pidfile /run/gitlabnssd.pid --exec /bin/gitlabnssd; then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        ;;
  stop)
        log_daemon_msg "Stopping GitLab Daemon" "gitlabnssd" || true
        if start-stop-daemon --stop --quiet --oknodo --pidfile /run/gitlabnssd.pid --exec /bin/gitlabnssd; then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        ;;

  reload|force-reload)
        log_daemon_msg "Reloading GitLab Daemon" "gitlabnssd" || true
        if start-stop-daemon --stop --signal 1 --quiet --oknodo --pidfile /run/gitlabnssd.pid --exec /bin/gitlabnssd; then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        ;;

  restart)
        check_privsep_dir
        log_daemon_msg "Restarting GitLab Daemon" "gitlabnssd" || true
        start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /run/gitlabnssd.pid --exec /bin/gitlabnssd
        check_dev_null log_end_msg
        if start-stop-daemon --start --quiet --oknodo --chuid 0:0 --pidfile /run/gitlabnssd.pid --exec /bin/gitlabnssd; then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        ;;

  try-restart)
        check_privsep_dir
        log_daemon_msg "Restarting GitLab Daemon" "gitlabnssd" || true
        RET=0
        start-stop-daemon --stop --quiet --retry 30 --pidfile /run/gitlabnssd.pid --exec /bin/gitlabnssd || RET="$?"
        case $RET in
            0)
                # old daemon stopped
                check_dev_null log_end_msg
                if start-stop-daemon --start --quiet --oknodo --chuid 0:0 --pidfile /run/gitlabnssd.pid --exec /bin/gitlabnssd; then
                    log_end_msg 0 || true
                else
                    log_end_msg 1 || true
                fi
                ;;
            1)
                # daemon not running
                log_progress_msg "(not running)" || true
                log_end_msg 0 || true
                ;;
            *)
                # failed to stop
                log_progress_msg "(failed to stop)" || true
                log_end_msg 1 || true
                ;;
        esac
        ;;

  status)
        status_of_proc -p /run/gitlabnssd.pid /bin/gitlabnssd gitlabnssd && exit 0 || exit $?
        ;;

  *)
        log_action_msg "Usage: /etc/init.d/gitlabnssd {start|stop|reload|force-reload|restart|try-restart|status}" || true
        exit 1
esac

exit 0